server:
   port: 8080

spring:
  application:
    name: api-gateway
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          
        - id: booking-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/bookings/**

        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/payments/**

        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/notifications/**